import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import React from "react"
import Navbar from "./components/layout/navbar"
import Footer from "./components/layout/footer"
import "leaflet/dist/leaflet.css"

/* Google Fonts */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

/* Local Font */
const ekhayaFont = localFont({
  src: "../public/fonts/EkhayaDisplayFont.otf",
  variable: "--font-ekhaya",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Ekhaya Meat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${ekhayaFont.variable}
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
