import type { Metadata } from "next"
import { Geist, Geist_Mono, Montserrat } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import React from "react"
import Navbar from "./components/layout/navbar"
import Footer from "./components/layout/footer"
import "leaflet/dist/leaflet.css"

/* Google Fonts */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

/* Montserrat (body text) */
// const montserrat = Montserrat({
// subsets: ["latin"],
// weight: ["400", "500", "600", "700"],
// variable: "--font-montserrat",
// display: "swap",
// })

/* Local Ekhaya font (headings) */
const ekhayaFont = localFont({
  src: "../public/fonts/EkhayaDisplayFont.otf",
  variable: "--font-ekhaya",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Ekhaya Meat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`scroll-smooth`}>
      <body
        className={`
          antialiased
          ${geistSans.variable}
          ${geistMono.variable}
        `}
      >
        <Navbar />
        <div className={`${ekhayaFont.variable} [&_h1]:font-ekhaya [&_h2]:font-ekhaya [&_h3]:font-ekhaya [&_h4]:font-ekhaya [&_h5]:font-ekhaya [&_h6]:font-ekhaya`}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
